In [90]:
import pandas as pd
import numpy as np

In [6]:
obj = pd.Series([4, 7, -5, 3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
type(obj)

pandas.core.series.Series

In [10]:
obj.keys()

RangeIndex(start=0, stop=4, step=1)

In [15]:
obj_values = obj.values

In [17]:
obj_values

array([ 4,  7, -5,  3], dtype=int64)

In [16]:
type(obj_values)

numpy.ndarray

In [12]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
obj1 = pd.Series([4, 7, -5, 3],  index=['a', 'b', 'c', 'd'])

In [19]:
obj1

a    4
b    7
c   -5
d    3
dtype: int64

In [20]:
obj1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [21]:
'c' in obj1

True

In [31]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [32]:
sdate = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [34]:
obj4 = pd.Series(sdate, index=states)

In [35]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [36]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [40]:
pd.NA

<NA>

In [42]:
type(pd.NA)

pandas._libs.missing.NAType

In [43]:
obj1 + obj4

California   NaN
Ohio         NaN
Oregon       NaN
Texas        NaN
a            NaN
b            NaN
c            NaN
d            NaN
dtype: float64

In [45]:
obj4.name = 'population'

In [46]:
obj4.index.name = 'state'


In [47]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [48]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [49]:
frame = pd.DataFrame(data)

In [50]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [51]:
pd.DataFrame(data, columns=['state', 'pop'])

state  pop
0    Ohio  1.5
1    Ohio  1.7
2    Ohio  3.6
3  Nevada  2.4
4  Nevada  2.9
5  Nevada  3.2

In [52]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                            index=['one', 'two', 'three', 'four', 'five', 'six'])


In [53]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [54]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [55]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [57]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [56]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [59]:
frame2['debt'] = 20.55

In [60]:
frame2['debt']

one      20.55
two      20.55
three    20.55
four     20.55
five     20.55
six      20.55
Name: debt, dtype: float64

In [61]:
frame2.debt.three = 66.77

C:\Users\Muwaffuq\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [63]:
frame2['debt']

one      20.55
two      20.55
three    66.77
four     20.55
five     20.55
six      20.55
Name: debt, dtype: float64

In [64]:
frame2['debt']['two'] = 57

C:\Users\Muwaffuq\AppData\Local\Temp/ipykernel_9076/714716981.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2['debt']['two'] = 57


In [65]:
frame2.loc['debt', 'one'] = 11

In [69]:
frame2.loc['debt', 'one']

11.0

In [67]:
frame2['debt']

one      20.55
two      57.00
three    66.77
four     20.55
five     20.55
six      20.55
debt       NaN
Name: debt, dtype: float64

In [71]:
frame2.loc['debt']

year      NaN
state     NaN
pop       NaN
debt      NaN
one      11.0
Name: debt, dtype: object

In [72]:
frame2

year   state  pop   debt   one
one    2000.0    Ohio  1.5  20.55   NaN
two    2001.0    Ohio  1.7  57.00   NaN
three  2002.0    Ohio  3.6  66.77   NaN
four   2001.0  Nevada  2.4  20.55   NaN
five   2002.0  Nevada  2.9  20.55   NaN
six    2003.0  Nevada  3.2  20.55   NaN
debt      NaN     NaN  NaN    NaN  11.0

In [77]:
year_column = frame2['year']

In [78]:
type(year_column)

pandas.core.series.Series

In [79]:
year_column

one      2000.0
two      2001.0
three    2002.0
four     2001.0
five     2002.0
six      2003.0
debt        NaN
Name: year, dtype: float64

In [80]:
frame2

year   state  pop   debt   one
one    2000.0    Ohio  1.5  20.55   NaN
two    2001.0    Ohio  1.7  57.00   NaN
three  2002.0    Ohio  3.6  66.77   NaN
four   2001.0  Nevada  2.4  20.55   NaN
five   2002.0  Nevada  2.9  20.55   NaN
six    2003.0  Nevada  3.2  20.55   NaN
debt      NaN     NaN  NaN    NaN  11.0

In [82]:
frame2.drop(columns=['one'], inplace=True)

In [84]:
frame2

year   state  pop   debt
one    2000.0    Ohio  1.5  20.55
two    2001.0    Ohio  1.7  57.00
three  2002.0    Ohio  3.6  66.77
four   2001.0  Nevada  2.4  20.55
five   2002.0  Nevada  2.9  20.55
six    2003.0  Nevada  3.2  20.55
debt      NaN     NaN  NaN    NaN

In [87]:
frame2.drop(index='debt', inplace=True)


In [88]:
frame2

year   state  pop   debt
one    2000.0    Ohio  1.5  20.55
two    2001.0    Ohio  1.7  57.00
three  2002.0    Ohio  3.6  66.77
four   2001.0  Nevada  2.4  20.55
five   2002.0  Nevada  2.9  20.55
six    2003.0  Nevada  3.2  20.55

In [89]:
frame2['debt']

one      20.55
two      57.00
three    66.77
four     20.55
five     20.55
six      20.55
Name: debt, dtype: float64

In [92]:
frame2['debt'] = np.arange(6.)

In [93]:
frame2['debt']

one      0.0
two      1.0
three    2.0
four     3.0
five     4.0
six      5.0
Name: debt, dtype: float64

In [94]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [95]:
frame2['debt'] = val

In [96]:
frame2

year   state  pop  debt
one    2000.0    Ohio  1.5   NaN
two    2001.0    Ohio  1.7  -1.2
three  2002.0    Ohio  3.6   NaN
four   2001.0  Nevada  2.4  -1.5
five   2002.0  Nevada  2.9  -1.7
six    2003.0  Nevada  3.2   NaN

In [98]:
frame2['eastern'] = frame2.state == 'Ohio'

In [99]:
frame2

year   state  pop  debt  eastern
one    2000.0    Ohio  1.5   NaN     True
two    2001.0    Ohio  1.7  -1.2     True
three  2002.0    Ohio  3.6   NaN     True
four   2001.0  Nevada  2.4  -1.5    False
five   2002.0  Nevada  2.9  -1.7    False
six    2003.0  Nevada  3.2   NaN    False

In [100]:
frame2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [104]:
del(frame2['eastern'])


In [105]:
frame2

year   state  pop  debt
one    2000.0    Ohio  1.5   NaN
two    2001.0    Ohio  1.7  -1.2
three  2002.0    Ohio  3.6   NaN
four   2001.0  Nevada  2.4  -1.5
five   2002.0  Nevada  2.9  -1.7
six    2003.0  Nevada  3.2   NaN

In [106]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
          'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


In [108]:
frame3 = pd.DataFrame(pop)

In [109]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [110]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [111]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [125]:
pd.DataFrame(pop, index=[2001, 2002, 2003])


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [126]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}


In [127]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [116]:
frame3['Ohio']

2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [118]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [119]:
frame3['Nevada']

2001    2.4
2002    2.9
2000    NaN
Name: Nevada, dtype: float64

In [120]:
frame3['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [115]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [128]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [129]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [130]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [131]:
frame2.values

array([[2000.0, 'Ohio', 1.5, nan],
       [2001.0, 'Ohio', 1.7, -1.2],
       [2002.0, 'Ohio', 3.6, nan],
       [2001.0, 'Nevada', 2.4, -1.5],
       [2002.0, 'Nevada', 2.9, -1.7],
       [2003.0, 'Nevada', 3.2, nan]], dtype=object)

In [136]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [137]:
obj

a    0
b    1
c    2
dtype: int64

In [138]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [139]:
index = obj.index


In [140]:
index

Index(['a', 'b', 'c'], dtype='object')

In [141]:
index[1:]

Index(['b', 'c'], dtype='object')

In [142]:
index[1]

'b'

In [143]:
labels = pd.Index(np.arange(3))

In [144]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [145]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)


In [146]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [147]:
obj2.index is labels

True

In [148]:
obj2.index

Int64Index([0, 1, 2], dtype='int64')

In [149]:
labels


Int64Index([0, 1, 2], dtype='int64')

In [150]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [151]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [152]:
'Ohio' in frame3.columns

True

In [153]:
2003 in frame3.columns

False

In [154]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])


In [156]:
dup_labels


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')