In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[6,7,8]])

In [ ]:
a

In [ ]:
a[0,2]

In [ ]:
a[:,1]

In [ ]:
a[1,:]

In [ ]:
b = [a, [1,2,3]]

In [ ]:
b

In [ ]:
b[0,0]

In [ ]:
b[0]

In [ ]:
b[0][0,0]

In [ ]:
type(b[0])

In [ ]:
b[1]

In [ ]:
type(b[1])

In [ ]:
type(b)

In [ ]:
c = np.array(a, [1,2,3])

In [ ]:
a

In [ ]:
a[2] = np.array([8,9,4])

In [ ]:
dir(a)

In [ ]:
a.item

In [ ]:
a.item(1)

In [ ]:
a

In [ ]:
a.item(2)

In [ ]:
a.item(5)

In [ ]:
a.all

In [ ]:
a.all()

In [ ]:
all(a)

In [ ]:
v = np.array([1,2,3])

In [ ]:
v

In [ ]:
dir(np)

In [ ]:
d = np.vectorize([1,2,3])

In [ ]:
d

In [ ]:
who

In [ ]:
whos

In [ ]:
help(np.zeros)

In [ ]:
help(np.ones)

In [ ]:
z = np.zeros(2, dtype=int)

In [ ]:
z

In [ ]:
np.ones(3, dtype=int)

In [ ]:
np

In [ ]:
a.dump(1)

In [ ]:
a.append([4,5,6])

In [ ]:
help(np.append)

In [ ]:
np.append(a, [5,4,7])

In [ ]:
a

In [ ]:
np.append(a, [8,9,4], axis=1)

In [ ]:
a

In [ ]:
f = np.array([[i for i in range(6)],[i for i in range(6,12)]])

In [89]:
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [90]:
f[:,1]

array([1, 7])

In [91]:
f[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [103]:
r = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [104]:
r

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [99]:
r[0]

array([[1, 2],
       [3, 4]])

In [100]:
r[1]

array([[5, 6],
       [7, 8]])

In [101]:
r[0,0,1]

2

In [105]:
r[:,1,:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [112]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [114]:
np.full((2,2),0)

array([[0, 0],
       [0, 0]])