In [ ]:
import numpy as np

In [19]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [23]:
list1 = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(list1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
list1[1, 5]

13

In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b.shape

(2, 3)

In [8]:
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [11]:
a.Type

AttributeError: 'numpy.ndarray' object has no attribute 'Type'

In [15]:
a.dtype

dtype('int16')

In [16]:
a.typesize

AttributeError: 'numpy.ndarray' object has no attribute 'typesize'

In [20]:
a.itemsize

4

In [21]:
a.size

3

In [22]:
a.nbytes

12

In [18]:
b.dtype

dtype('int32')